language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    - composer self-update

install:
    - composer install

before_script:
    - mysql -uroot -e 'SET @@global.sql_mode = TRADITIONAL; CREATE DATABASE runalyze_unittest;';
    - mysql runalyze_unittest < inc/install/structure.sql

script:
    - phpunit --colors -c tests/config.xml
