start:
    resource: "@RunalyzeCoreBundle/Controller/DefaultController.php"
    type:    annotation
databrowser:
    resource: "@RunalyzeCoreBundle/Controller/DatabrowserController.php"
    type:    annotation
security:
    resource: "@RunalyzeCoreBundle/Controller/SecurityController.php"
    type:    annotation
logout:
    path:   /logout
configuration:
    resource: "@RunalyzeCoreBundle/Controller/ConfigurationController.php"
    prefix:   /configuration
    type:    annotation