start:
    resource: "@RunalyzeCoreBundle/Controller/DefaultController.php"
    type:    annotation
security:
    resource: "@RunalyzeCoreBundle/Controller/SecurityController.php"
    type:    annotation
logout:
    path:   /logout
