services:
    runalyze.configuration:
        class: Runalyze\CoreBundle\Service\Configuration
        arguments: [@doctrine.orm.entity_manager] 
    runalyze.dataset:
        class: Runalyze\CoreBundle\Service\Dataset
        arguments: [@doctrine.orm.entity_manager] 
    runalyze.training:
        class: Runalyze\CoreBundle\Service\ActivityView
        scope: prototype
    runalyze.sport:
        class: Runalyze\CoreBundle\Service\Sport
        arguments: [@doctrine.orm.entity_manager] 
        
