# config/routes.yml

# Default
app:
    path: /
    defaults: { _controller: 'Runalyze\HomeController::appAction' }
activity:
    path: /activity
    defaults: { _controller: 'Runalyze\ActivityController::homeAction' }
    
login:
    path: /login
    defaults: { _controller: 'Runalyze\HomeController::loginAction' }
    
logout:
    path: /logout
    defaults: { _controller: 'Runalyze\HomeController::logoutAction' }
    
help:
    path: /help
    defaults: { _controller: 'Runalyze\HomeController::helpAction' }
    
register:
    path: /register
    defaults: { _controller: 'Runalyze\HomeController::registerAction' }
    
forgotpw:
    path: /forgotpw
    defaults: { _controller: 'Runalyze\HomeController::forgotPwAction' }

# Account activation, Deletion, Forgot password
useractivate:
    path: /activate/{hash}
    defaults: { _controller: 'Runalyze\HomeController::activateAction' }
    
userdelete:
    path: /delete/{hash}
    defaults: { _controller: 'Runalyze\HomeController::deleteAction' }
    
userforgotpw:
    path: /changepassword/{hash}
    defaults: { _controller: 'Runalyze\HomeController::changePasswordAction' }
 
# Settings 
    
settingswithkey:
    path: /settings/{key}
    defaults: { _controller: 'Runalyze\SettingsController::DefaultAction' }
    
settings:
    path: /settings
    defaults: { _controller: 'Runalyze\SettingsController::DefaultAction' }
    
# Activity
activity_edit:
    path: /activity/edit/{id}
    defaults: { _controller: 'Runalyze\ActivityController::editAction' }
    
activity_search:
    path: /activity/search
    defaults: { _controller: 'Runalyze\ActivityController::searchAction' }
    
activity_export:
    path: /activity/export/{id}
    defaults: { _controller: 'Runalyze\ActivityController::exportAction' }
    
activity_create:
    path: /activity/create
    defaults: { _controller: 'Runalyze\ActivityController::createAction' }    
    
activity_elevation_info:
    path: /activity/elevationinfo/{id}
    defaults: { _controller: 'Runalyze\ActivityController::elevationInfoAction' }   
    
activity_rounds:
    path: /activity/rounds/{id}
    defaults: { _controller: 'Runalyze\ActivityController::roundsAction' }   
    
activity_vdot:
    path: /activity/vdot/{id}
    defaults: { _controller: 'Runalyze\ActivityController::vdotAction' }   
    
activity_elevationCorrection:
    path: /activity/elevationCorrection/{id}
    defaults: { _controller: 'Runalyze\ActivityController::ElevationCorrectionAction' }    

activityview:
    path: /activity/{id}
    defaults: { _controller: 'Runalyze\ActivityController::viewAction' } 
    
#Plots
plot_save:
    path: /plot/save
    defaults: { _controller: 'Runalyze\PlotController::saveAction' }  
    
plot_sum:
    path: /plot/sum
    defaults: { _controller: 'Runalyze\PlotController::sumAction' }  
    
plot_sum_type:
    path: /plot/sum/{type}
    defaults: { _controller: 'Runalyze\PlotController::sumAction' }   
    

#Plugin, Panels, TOols
panel_move:
    path: /plugin/move/{id}
    defaults: { _controller: 'Runalyze\PluginController::PanelMoveAction' }
panel_clap:
    path: /plugin/clap/{id}
    defaults: { _controller: 'Runalyze\PluginController::PanelClapAction' }
panel_display:
    path: /plugin/display
    defaults: { _controller: 'Runalyze\PluginController::PanelDisplayAction' }

tools:
    path: /tools
    defaults: { _controller: 'Runalyze\PluginController::toolsAction' }
    
plugin:
    path: /plugin/{id}
    defaults: { _controller: 'Runalyze\PluginController::DefaultAction' }
    
plugin_install:
    path: /plugin/install/{key}
    defaults: { _controller: 'Runalyze\PluginController::installAction' }
    
plugin_uninstall:
    path: /plugin/uninstall/{key}
    defaults: { _controller: 'Runalyze\PluginController::uninstallAction' }
    
pluginconfig:
    path: /plugin/config/{id}
    defaults: { _controller: 'Runalyze\PluginController::ConfigAction' }
    
databrowser:
    path: /databrowser
    defaults: { _controller: 'Runalyze\DatabrowserController::DefaultAction' }
    
site:
    path: /{sitename}
    defaults: { _controller: 'Runalyze\HomeController::SiteAction' }
#plugin routes
plugin_panel_prognose:
    prefix: /plugin/panel/prognose
    resource: ../plugin/RunalyzePluginPanel_Prognose/routes.yml

plugin_panel_rechenspiele:
    prefix: /plugin/panel/rechenspiele
    resource: ../plugin/RunalyzePluginPanel_Rechenspiele/routes.yml
#others
facebook_metacourse:
    path: /activity/metacourse/{id}
    defaults: { _controller: 'Runalyze\ActivityController::metaCourseAction' }  
    
#shared
shared_activity:
    path: /shared/{id}
    defaults: { _controller: 'Runalyze\SharedController::ActivityAction' } 
shared_list:
    path: /shared/{user}/
    defaults: { _controller: 'Runalyze\SharedController::ListAction' } 
