# config/routes.yml

app:
    path: /
    defaults: { _controller: 'Runalyze\HomeController::appAction' }
activity:
    path: /activity
    defaults: { _controller: 'Runalyze\ActivityController::homeAction' }
    
login:
    path: /login
    defaults: { _controller: 'Runalyze\HomeController::loginAction' }
    
register:
    path: /register
    defaults: { _controller: 'Runalyze\HomeController::registerAction' }
    
forgotpw:
    path: /forgotpw
    defaults: { _controller: 'Runalyze\HomeController::forgotPwAction' }
   
useractivate:
    path: /activate/{hash}
    defaults: { _controller: 'Runalyze\HomeController::activateAction' }
    
userdelete:
    path: /delete/{hash}
    defaults: { _controller: 'Runalyze\HomeController::deleteAction' }
    
userforgotpw:
    path: /changepassword/{hash}
    defaults: { _controller: 'Runalyze\HomeController::changePasswordAction' }
    
settings:
    path: /settings/{key}
    defaults: { _controller: 'Runalyze\SettingsController::DefaultAction' }
    
site:
    path: /{sitename}
    defaults: { _controller: 'Runalyze\HomeController::SiteAction' }