# config/routes.yml

app:
    path: /
    defaults: { _controller: 'Runalyze\HomeController::appAction' }
activity:
    path: /activity
    defaults: { _controller: 'Runalyze\ActivityController::homeAction' }
    
login:
    path: /login
    defaults: { _controller: 'Runalyze\HomeController::loginAction' }
    
logout:
    path: /logout
    defaults: { _controller: 'Runalyze\HomeController::logoutAction' }
    
help:
    path: /help
    defaults: { _controller: 'Runalyze\HomeController::helpAction' }
    
register:
    path: /register
    defaults: { _controller: 'Runalyze\HomeController::registerAction' }
    
forgotpw:
    path: /forgotpw
    defaults: { _controller: 'Runalyze\HomeController::forgotPwAction' }
   
useractivate:
    path: /activate/{hash}
    defaults: { _controller: 'Runalyze\HomeController::activateAction' }
    
userdelete:
    path: /delete/{hash}
    defaults: { _controller: 'Runalyze\HomeController::deleteAction' }
    
userforgotpw:
    path: /changepassword/{hash}
    defaults: { _controller: 'Runalyze\HomeController::changePasswordAction' }
 
tools:
    path: /tools
    defaults: { _controller: 'Runalyze\PluginController::toolsAction' }
 
settings:
    path: /settings
    defaults: { _controller: 'Runalyze\SettingsController::DefaultAction' }
    
settingswithkey:
    path: /settings/{key}
    defaults: { _controller: 'Runalyze\SettingsController::DefaultAction' }
     
activity_edit:
    path: /activity/edit
    defaults: { _controller: 'Runalyze\ActivityController::editAction' }
    
activity_search:
    path: /activity/search
    defaults: { _controller: 'Runalyze\ActivityController::searchAction' }
    
activity_create:
    path: /activity/create
    defaults: { _controller: 'Runalyze\ActivityController::createAction' }    

activityview:
    path: /activity/{id}
    defaults: { _controller: 'Runalyze\ActivityController::viewAction' } 
    
plot_sum:
    path: /plot/sum
    defaults: { _controller: 'Runalyze\PlotController::sumAction' }  
    
plot_sum_type:
    path: /plot/sum/{type}
    defaults: { _controller: 'Runalyze\PlotController::sumAction' }   
    
 
panel_move:
    path: /panel/move/{id}
    defaults: { _controller: 'Runalyze\PluginController::PanelMoveAction' }
panel_clap:
    path: /panel/clap/{id}
    defaults: { _controller: 'Runalyze\PluginController::PanelClapAction' }
panel_display:
    path: /plugin/display
    defaults: { _controller: 'Runalyze\PluginController::PanelDisplayAction' }

      
plugin:
    path: /plugin/{id}
    defaults: { _controller: 'Runalyze\PluginController::DefaultAction' }
    
pluginconfig:
    path: /plugin/config/{id}
    defaults: { _controller: 'Runalyze\PluginController::ConfigAction' }
    
databrowser:
    path: /databrowser
    defaults: { _controller: 'Runalyze\DatabrowserController::DefaultAction' }
    
site:
    path: /{sitename}
    defaults: { _controller: 'Runalyze\HomeController::SiteAction' }