# config/routes.yml

app:
    path: /
    defaults: { _controller: 'Runalyze\HomeController::appAction' }
activity:
    path: /activity
    defaults: { _controller: 'Runalyze\ActivityController::homeAction' }
    
login:
    path: /login
    defaults: { _controller: 'Runalyze\HomeController::loginAction' }
    
settings:
    path: /settings/{key}
    defaults: { _controller: 'Runalyze\SettingsController::DefaultAction' }
    
site:
    path: /site/{sitename}
    defaults: { _controller: 'Runalyze\HomeController::SiteAction' }